### ISSUE TITLE
Cant use the messages feature

### ISSUE THREAD

**Issue by Fluffpumpkin** [jblanked/FlipSocial#2]
Steps to reproduce:
-  go to messages tab
- click messages
- nothing happens

I am using version 0.6.2

I attempted to log out and log back in but I promptly forgot my password so I wasn't able to test that

**Comment by jblanked** [comment]
Thanks for reporting the issue. Log back in and see if you can view your messages.

**Comment by jblanked** [comment]
What I suggested above probably won’t work. I’ve just released version 0.6.3, which addresses this issue. Thank you for your feedback!

**Comment by jblanked** [comment]
Version 0.6.3 has been released in the app catalog: https://lab.flipper.net/apps/flip_social
